### ISSUE TITLE
Changelog check marks overlap text during the animation, then pop into place

### ISSUE THREAD

**Issue by CatThingy** [syntechsrobotics/syntechsrobotics.github.io#3]
Steps to reproduce: 
1. Go to https://syntechsrobotics.ca/changelog.html
2. Scroll down

Image:
![Example of the bug](https://user-images.githubusercontent.com/32040424/75116644-6b284e80-561f-11ea-9785-159fcc49df8a.png)

**Comment by bluejunimo** [comment]
unfix-able with my little knowledge

**Comment by CatThingy** [comment]
maybe the issue is with the text instead of the checks, have you tried disabling the animations on those?

**Comment by bluejunimo** [comment]
New changelog design, fixed!
